In [1]:
import pandas as pd
import seaborn as sn
import numpy as np
import matplotlib.pyplot as plt, re
import io
import nltk

In [2]:
df = pd.read_csv(r'C:\Users\utkar\OneDrive\Desktop\Machine Learning\Customerfeedback\Restaurant_Reviews.tsv', delimiter = '\t')

In [3]:
df.head(1005)

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [4]:
feedback = df

In [5]:
feedback.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [6]:
import nlp_tools
import contractions

In [7]:
feedback['cleanReviews'] = feedback['Review'].apply(contractions.expand_contraction)

In [8]:
feedback['cleanReviews'] = feedback['cleanReviews'].apply(nlp_tools.lemmatization_sentence)

In [9]:
like_dislike_list = feedback['cleanReviews'].tolist()

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv = CountVectorizer()

In [138]:
cv = cv.fit(like_dislike_list)

In [139]:
filename = r'C:\Users\utkar\OneDrive\Desktop\Machine Learning\Customerfeedback\count_vectorizer.pkl'

In [140]:
pickle.dump(cv, open(filename, 'wb'))

In [13]:
X = cv.transform(like_dislike_list).toarray()

In [14]:
len(cv.get_feature_names())

1750

In [15]:
y = feedback['Liked'].values

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y)

In [17]:
import lazypredict
from lazypredict.Supervised import LazyClassifier

In [18]:
clf = LazyClassifier(verbose=0,ignore_warnings=True)
models, predictions = clf.fit(x_train, x_test, y_train, y_test)
models

100%|██████████| 29/29 [00:27<00:00,  1.06it/s]


Accuracy  Balanced Accuracy  ROC AUC  F1 Score  \
Model                                                                           
LogisticRegression                 0.81               0.82     0.82      0.81   
ExtraTreesClassifier               0.81               0.81     0.81      0.81   
CalibratedClassifierCV             0.80               0.81     0.81      0.80   
PassiveAggressiveClassifier        0.80               0.80     0.80      0.80   
BernoulliNB                        0.79               0.79     0.79      0.79   
BaggingClassifier                  0.79               0.79     0.79      0.79   
LinearSVC                          0.78               0.78     0.78      0.78   
AdaBoostClassifier                 0.78               0.78     0.78      0.78   
XGBClassifier                      0.77               0.77     0.77      0.77   
RidgeClassifierCV                  0.77               0.77     0.77      0.77   
NuSVC                              0.76               0.77     0.77      0.76   
NearestCentroid                    0.76               0.77     0.77      0.76   
RandomForestClassifier             0.76               0.76     0.76      0.76   
DecisionTreeClassifier             0.75               0.74     0.74      0.75   
Perceptron                         0.73               0.73     0.73      0.73   
RidgeClassifier                    0.72               0.73     0.73      0.72   
SVC                                0.72               0.72     0.72      0.71   
SGDClassifier                      0.69               0.70     0.70      0.68   
LGBMClassifier                     0.69               0.69     0.69      0.69   
GaussianNB                         0.67               0.68     0.68      0.66   
ExtraTreeClassifier                0.67               0.67     0.67      0.67   
LinearDiscriminantAnalysis         0.66               0.66     0.66      0.66   
KNeighborsClassifier               0.54               0.55     0.55      0.49   
LabelSpreading                     0.54               0.52     0.52      0.42   
LabelPropagation                   0.54               0.52     0.52      0.42   
QuadraticDiscriminantAnalysis      0.49               0.51     0.51      0.38   
DummyClassifier                    0.47               0.47     0.47      0.47   

                               Time Taken  
Model                                      
LogisticRegression                   0.27  
ExtraTreesClassifier                 1.41  
CalibratedClassifierCV               4.69  
PassiveAggressiveClassifier          0.36  
BernoulliNB                          0.24  
BaggingClassifier                    0.79  
LinearSVC                            0.67  
AdaBoostClassifier                   2.06  
XGBClassifier                        4.27  
RidgeClassifierCV                    0.69  
NuSVC                                1.98  
NearestCentroid                      0.14  
RandomForestClassifier               0.86  
DecisionTreeClassifier               0.45  
Perceptron                           0.15  
RidgeClassifier                      0.41  
SVC                                  1.96  
SGDClassifier                        0.21  
LGBMClassifier                       0.35  
GaussianNB                           0.17  
ExtraTreeClassifier                  0.18  
LinearDiscriminantAnalysis           1.78  
KNeighborsClassifier                 0.99  
LabelSpreading                       0.24  
LabelPropagation                     0.31  
QuadraticDiscriminantAnalysis        1.26  
DummyClassifier                      0.19

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
reg = LogisticRegression(random_state = 0)

In [21]:
model= reg.fit(x_train,y_train)

In [22]:
predicted_values = model.predict(x_test)

In [23]:
predicted_values

array([0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [24]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, predicted_values)

0.816

In [25]:
bad_review = 'The meal was not fullfiling'

clean_review = contractions.expand_contraction(bad_review)
lemma_review = nlp_tools.lemmatization_sentence(clean_review)
vector_review = cv.transform([lemma_review]).toarray()
review = model.predict(vector_review)
pred = model.predict_proba(vector_review)

In [26]:
pred

array([[0.84447189, 0.15552811]])

In [27]:
review

array([0], dtype=int64)

In [28]:
good_review = 'The meal was satisfying'

clean_review = contractions.expand_contraction(good_review)
lemma_review = nlp_tools.lemmatization_sentence(clean_review)
vector_review = cv.transform([lemma_review]).toarray()
review = model.predict(vector_review)
pred = model.predict_proba(vector_review)

In [29]:
pred

array([[0.38106051, 0.61893949]])

In [30]:
review

array([1], dtype=int64)

In [33]:
import speech_recognition as sr
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Speak Anything :")
    audio = r.listen(source)
    
    try:
        text = r.recognize_google(audio)
        
        print("You said : {}".format(text))
    except:
        print("Sorry could not recognize what you said")
        

Speak Anything :
You said : the meal was delicious


In [34]:
clean_review = contractions.expand_contraction(text)
lemma_review = nlp_tools.lemmatization_sentence(clean_review)
vector_review = cv.transform([lemma_review]).toarray()
review = model.predict(vector_review)
pred = model.predict_proba(vector_review)

In [35]:
pred

array([[0.15044037, 0.84955963]])

In [36]:
review

array([1], dtype=int64)

In [39]:
df.head(1005)

Review  Liked  \
0                              Wow... Loved this place.   1.00   
1                                    Crust is not good.   0.00   
2             Not tasty and the texture was just nasty.   0.00   
3     Stopped by during the late May bank holiday of...   1.00   
4     The selection on the menu was great and so wer...   1.00   
...                                                 ...    ...   
996                            Appetite instantly gone.   0.00   
997   Overall I was not impressed and would not go b...   0.00   
998   The whole experience was underwhelming, and I ...   0.00   
999   Then, as if I hadn't wasted enough of my life ...   0.00   
1000                             the meal was delicious   1.00   

                                           cleanReviews  
0                               wow ... love this place  
1                                     crust be not good  
2               not tasty and the texture be just nasty  
3     stop by during the late may bank holiday off r...  
4     the selection on the menu be great and so be t...  
...                                                 ...  
996                               appetite instantly go  
997    overall i be not impressed and would not go back  
998   the whole experience be underwhelming and i th...  
999   then a if i have not waste enough of my life t...  
1000                                                NaN  

[1001 rows x 3 columns]

In [40]:
df.loc[len(df), 'Review'] = text
df.loc[len(df) - 1, 'Liked'] = review[0]

In [41]:
df.head(1005)

Review  Liked  \
0                              Wow... Loved this place.   1.00   
1                                    Crust is not good.   0.00   
2             Not tasty and the texture was just nasty.   0.00   
3     Stopped by during the late May bank holiday of...   1.00   
4     The selection on the menu was great and so wer...   1.00   
...                                                 ...    ...   
997   Overall I was not impressed and would not go b...   0.00   
998   The whole experience was underwhelming, and I ...   0.00   
999   Then, as if I hadn't wasted enough of my life ...   0.00   
1000                             the meal was delicious   1.00   
1001                             the meal was delicious   1.00   

                                           cleanReviews  
0                               wow ... love this place  
1                                     crust be not good  
2               not tasty and the texture be just nasty  
3     stop by during the late may bank holiday off r...  
4     the selection on the menu be great and so be t...  
...                                                 ...  
997    overall i be not impressed and would not go back  
998   the whole experience be underwhelming and i th...  
999   then a if i have not waste enough of my life t...  
1000                                                NaN  
1001                                                NaN  

[1002 rows x 3 columns]

In [42]:
feedback = df

In [46]:
df = df.drop('cleanReviews', 1)

In [117]:
fields = [text, review[0]]

In [118]:
import csv

In [120]:
with open(r'C:\Users\utkar\OneDrive\Desktop\Machine Learning\Customerfeedback\Restaurant_Reviews.tsv','a') as fd:
    writer = csv.writer(fd, delimiter='\t')
    writer.writerow(fields)

In [121]:
feedback.tail()

Review  Liked  \
997   Overall I was not impressed and would not go b...   0.00   
998   The whole experience was underwhelming, and I ...   0.00   
999   Then, as if I hadn't wasted enough of my life ...   0.00   
1000                             the meal was delicious   1.00   
1001                             the meal was delicious   1.00   

                                           cleanReviews  
997    overall i be not impressed and would not go back  
998   the whole experience be underwhelming and i th...  
999   then a if i have not waste enough of my life t...  
1000                                                NaN  
1001                                                NaN

In [122]:
df.tail()

Review  Liked
997   Overall I was not impressed and would not go b...   0.00
998   The whole experience was underwhelming, and I ...   0.00
999   Then, as if I hadn't wasted enough of my life ...   0.00
1000                             the meal was delicious   1.00
1001                             the meal was delicious   1.00

In [123]:
import pickle

In [124]:
filename = r'C:\Users\utkar\OneDrive\Desktop\Machine Learning\Customerfeedback\feedbackmodel.pkl'

In [125]:
pickle.dump(model, open(filename, 'wb'))

In [126]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(x_test, y_test)
print(result)

0.816


In [127]:
prediction = loaded_model.predict(x_test)

In [128]:
prediction

array([0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [130]:
import speech_recognition as sr
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Speak Anything :")
    audio = r.listen(source)
    
    try:
        text = r.recognize_google(audio)
        
        print("You said : {}".format(text))
    except:
        print("Sorry could not recognize what you said")
        

Speak Anything :
You said : that food tasted bad


In [131]:
clean_review = contractions.expand_contraction(text)
lemma_review = nlp_tools.lemmatization_sentence(clean_review)
vector_review = cv.transform([lemma_review]).toarray()
review = loaded_model.predict(vector_review)
pred = loaded_model.predict_proba(vector_review)

In [132]:
review

array([0], dtype=int64)

In [133]:
pred

array([[0.9484469, 0.0515531]])

In [134]:
df.loc[len(df), 'Review'] = text
df.loc[len(df) - 1, 'Liked'] = review[0]

In [135]:
df.tail()

Review  Liked
998   The whole experience was underwhelming, and I ...   0.00
999   Then, as if I hadn't wasted enough of my life ...   0.00
1000                             the meal was delicious   1.00
1001                             the meal was delicious   1.00
1002                               that food tasted bad   0.00